[project]
name = "test-renovate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.0"
dependencies = [
    "django==4.2.24",
    "django-cors-headers==4.2.0",
    "django-csp==3.8",
    "pandas==2.2.1",
]
