[project]
name = "test-renovate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"

[tool.poetry.dependencies]
django = "5.2.9"
django-cors-headers = "4.2.0"
django-csp = "3.7"
pandas = "2.2.1"
python = "~3.12"
